### ISSUE TITLE
Seems websocket is not accessible

### ISSUE THREAD

**Issue by qianbin** [mirei83/VeChain-PublicNodes#1]
When I tried to access wss://testnet.veblocks.net/subscriptions/beat in chrome, error got: 'failed: Error during WebSocket handshake: Unexpected response code: 400'

**Comment by mirei83** [comment]
Issue is resolved for solo.veblocks.net, testnet.veblocks.net and mainnet.veblocks.net. 
Websockets can be used like:

curl --include --no-buffer --header "Connection: Upgrade" --header "Upgrade: websocket" --header "Host: mainnet.veblocks.net" --header "Origin: https://mainnet.veblocks.net" --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" --header "Sec-WebSocket-Version: 13" https://mainnet.veblocks.net/subscriptions/beat
